apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: realtime-monitoring-keyvault
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure

  secretObjects:
    - secretName: realtime-monitoring-kv-secrets
      type: Opaque
      data:
        - objectName: postgres-admin-password
          key: SPRING_DATASOURCE_PASSWORD

  parameters:
    clientID: "{{ .Values.azure.workloadIdentity.clientId }}"
    keyvaultName: "{{ .Values.azure.keyVault.name }}"
    tenantId: "{{ .Values.azure.tenantId }}"

    objects: |
      array:
        - |
          objectName: postgres-admin-password
          objectType: secret
          objectVersion: ""