apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: realtime-monitoring-keyvault
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure

  secretObjects:
    - secretName: realtime-monitoring-kv-secrets
      type: Opaque
      data:
        - objectName: postgres-admin-password
          key: SPRING_DATASOURCE_PASSWORD
        - objectName: config-repo-github-token
          key: GITHUB_TOKEN


          
  parameters:
    usePodIdentity: "false"
    clientID: "{{ .Values.azure.workloadIdentity.clientId }}"
    keyvaultName: "{{ .Values.azure.keyVault.name }}"
    tenantId: "{{ .Values.azure.tenantId }}"

    objects: |
      array:
        - |
          objectName: postgres-admin-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: config-repo-github-token
          objectType: secret
          objectVersion: ""
          

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: device-service-keyvault
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "{{ .Values.azure.workloadIdentity.clientId }}"
    keyvaultName: "{{ .Values.azure.keyVault.name }}"
    tenantId: "{{ .Values.azure.tenantId }}"
    objects: |
      array:
        - |
          objectName: mqtt-ca-crt
          objectType: secret
          objectAlias: ca.crt
          objectVersion: ""
        - |
          objectName: mqtt-backend-crt
          objectType: secret
          objectAlias: backend.crt
          objectVersion: ""
        - |
          objectName: mqtt-backend-key
          objectType: secret
          objectAlias: backend.key
          objectVersion: ""
        - |
          objectName: pki-ca-crt
          objectType: secret
          objectAlias: pki-ca.crt
          objectVersion: ""
        - |
          objectName: pki-ca-key
          objectType: secret
          objectAlias: pki-ca.key
          objectVersion: ""