apiVersion: v1
kind: ServiceAccount
metadata:
  name: realtime-monitoring-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.azure.workloadIdentity.clientId }}"