services:
  auth:
    image: chedlyrebai/authentification-server:latest
    port: 9080
    replicas: 2
    database: true
  config:
    image: chedlyrebai/config-server:latest
    port: 9000
    replicas: 1
  device:
    image: chedlyrebai/device-service:latest
    port: 9005
    replicas: 2
    database: true
  discovery:
    image: chedlyrebai/discovery-server:latest
    port: 8761
    replicas: 1
    serviceName: discovery-server
  frontend:
    image: chedlyrebai/frontend:latest
    port: 4173
    replicas: 2
    public: true
    healthPath: /
  gateway:
    image: chedlyrebai/getaway-service:latest
    port: 8222
    replicas: 2
    public: false
    serviceName: gateway
  notifications:
    image: chedlyrebai/notification-server:latest
    port: 8085
    replicas: 2
    database: true
  query:
    image: chedlyrebai/query-service:latest
    port: 9007
    replicas: 2
    database: true
  tenant:
    image: chedlyrebai/tenant-service:latest
    port: 9004
    replicas: 2
    database: true
  user:
    image: chedlyrebai/usermanagement-service:latest
    port: 9003
    grpcPort: 9095
    replicas: 2
    database: true

imagePullPolicy: Always
configMapName: realtime-monitoring-config
secretName: realtime-monitoring-secrets

appConfig:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  SPRING_CLOUD_CONFIG_ENABLED: "true"
  SPRING_CLOUD_CONFIG_FAIL_FAST: "true"
  SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS: "240"
  SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL: "1000"
  SPRING_CLOUD_CONFIG_RETRY_MULTIPLIER: "1.5"
  SPRING_CLOUD_CONFIG_RETRY_MAX_INTERVAL: "5000"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_REDIS_DATA_HOST: "redis"
  SPRING_REDIS_DATA_PORT: "6379"
  SPRING_DATASOURCE_URL_AUTH: "jdbc:postgresql://rtm-postgres.postgres.database.azure.com:5432/jwt?sslmode=require"
  SPRING_DATASOURCE_URL_DEVICE: "jdbc:postgresql://rtm-postgres.postgres.database.azure.com:5432/device_management?sslmode=require"
  SPRING_DATASOURCE_URL_NOTIFICATIONS: "jdbc:postgresql://rtm-postgres.postgres.database.azure.com:5432/notification?sslmode=require"
  SPRING_DATASOURCE_URL_QUERY: "jdbc:postgresql://rtm-postgres.postgres.database.azure.com:5432/read_database?sslmode=require"
  SPRING_DATASOURCE_URL_TENANT: "jdbc:postgresql://rtm-postgres.postgres.database.azure.com:5432/tenant_mang?sslmode=require"
  SPRING_DATASOURCE_URL_USER: "jdbc:postgresql://rtm-postgres.postgres.database.azure.com:5432/postgres?sslmode=require"

redis:
  enabled: true
  image: redis:7-alpine

kafka:
  image: confluentinc/cp-kafka:7.6.1

azure:
  workloadIdentity:
    clientId: "a9d7f4f9-6247-4cbb-bcfc-0eb9dc998659"

  keyVault:
    name: "rtm-kv-9bd0f37e"

  tenantId: "604f1a96-cbe8-43f8-abbf-f8eaf5d85730"