#   az keyvault secret set --vault-name rtm-kv-9bd0f37e   --name grafana-admin-password --value 'admin'
#   az keyvault secret set --vault-name rtm-kv-9bd0f37e  --name grafana-admin-user --value 'admin'
# =============================================================================
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-keyvault
  namespace: monitoring
spec:
  provider: azure
  secretObjects:
    - secretName: grafana-admin-secret
      type: Opaque
      data:
        - objectName: grafana-admin-user
          key: admin-user
        - objectName: grafana-admin-password
          key: admin-password
  parameters:
    usePodIdentity: "false"
    clientID: "a9d7f4f9-6247-4cbb-bcfc-0eb9dc998659"
    keyvaultName: "rtm-kv-9bd0f37e"
    tenantId: "604f1a96-cbe8-43f8-abbf-f8eaf5d85730"
    objects: |
      array:
        - |
          objectName: grafana-admin-user
          objectType: secret
          objectAlias: grafana-admin-user
          objectVersion: ""
        - |
          objectName: grafana-admin-password
          objectType: secret
          objectAlias: grafana-admin-password
          objectVersion: ""
